<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Planvexa.Database</RootNamespace>
    <AssemblyName>Planvexa.Database</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dbup-core" />
    <PackageReference Include="dbup-postgresql" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\*.sql" />
  </ItemGroup>

</Project>


