namespace Planvexa.Modules.Reporting.Domain;

using Planvexa.BuildingBlocks.Domain;
using Planvexa.BuildingBlocks.Exceptions;

/// <summary>
/// A named, owned, curated Portfolio: a chosen subset of the workspace's Spaces (<see cref="Members"/>,
/// id-only references per AGENTS.md rule 7 -- Spaces live in WorkManagement) whose combined
/// Health/Progress/Milestones/Risks/Budget rollup PortfolioService.GetReportAsync computes on demand
/// (never persisted). Same Name/OwnerUserId/IsPrivate shape as <see cref="Dashboard"/>; a private
/// portfolio is only visible to its owner.
/// </summary>
public sealed class Portfolio : Entity, IAggregateRoot, IWorkspaceOwned
{
    private readonly List<PortfolioMember> _members = new();

    private Portfolio()
    {
    }

    private Portfolio(
        Guid id, Guid workspaceId, string name, Guid ownerUserId, bool isPrivate, PortfolioStatus status,
        DateTimeOffset? startUtc, DateTimeOffset? targetEndUtc, DateTimeOffset nowUtc)
        : base(id)
    {
        WorkspaceId = workspaceId;
        Name = name;
        OwnerUserId = ownerUserId;
        IsPrivate = isPrivate;
        Status = status;
        StartUtc = startUtc;
        TargetEndUtc = targetEndUtc;
        CreatedAtUtc = nowUtc;
        UpdatedAtUtc = nowUtc;
    }

    public Guid WorkspaceId { get; private set; }
    public string Name { get; private set; } = string.Empty;
    public Guid OwnerUserId { get; private set; }
    public bool IsPrivate { get; private set; }
    public PortfolioStatus Status { get; private set; }
    public DateTimeOffset? StartUtc { get; private set; }
    public DateTimeOffset? TargetEndUtc { get; private set; }
    public DateTimeOffset CreatedAtUtc { get; private set; }
    public DateTimeOffset UpdatedAtUtc { get; private set; }

    public IReadOnlyList<PortfolioMember> Members => _members.AsReadOnly();

    public static Portfolio Create(
        Guid id, Guid workspaceId, string name, Guid ownerUserId, bool isPrivate, PortfolioStatus status,
        DateTimeOffset? startUtc, DateTimeOffset? targetEndUtc, DateTimeOffset nowUtc)
    {
        Guard.AgainstNullOrWhiteSpace(name, nameof(name));
        Guard.AgainstEmpty(ownerUserId, nameof(ownerUserId));
        return new Portfolio(id, workspaceId, name.Trim(), ownerUserId, isPrivate, status, startUtc, targetEndUtc, nowUtc);
    }

    public void Update(
        string? name, Guid? ownerUserId, bool? isPrivate, PortfolioStatus? status,
        DateTimeOffset? startUtc, DateTimeOffset? targetEndUtc, DateTimeOffset nowUtc)
    {
        if (!string.IsNullOrWhiteSpace(name))
        {
            Name = name.Trim();
        }

        if (ownerUserId.HasValue)
        {
            OwnerUserId = ownerUserId.Value;
        }

        if (isPrivate.HasValue)
        {
            IsPrivate = isPrivate.Value;
        }

        if (status.HasValue)
        {
            Status = status.Value;
        }

        if (startUtc.HasValue)
        {
            StartUtc = startUtc;
        }

        if (targetEndUtc.HasValue)
        {
            TargetEndUtc = targetEndUtc;
        }

        UpdatedAtUtc = nowUtc;
    }

    /// <summary>Replaces the full curated Space membership (ids pre-generated by the service, same
    /// shape as <see cref="Dashboard.ReplaceWidgets"/>). Duplicate space ids collapse to one row.</summary>
    public void ReplaceMembers(IEnumerable<(Guid Id, Guid SpaceId)> members, DateTimeOffset nowUtc)
    {
        _members.Clear();
        foreach (var m in members.DistinctBy(m => m.SpaceId))
        {
            _members.Add(PortfolioMember.Create(m.Id, Id, m.SpaceId));
        }

        UpdatedAtUtc = nowUtc;
    }

    /// <summary>Whether the given user may view this portfolio (owner-only when private).</summary>
    public bool CanBeViewedBy(Guid userId) => !IsPrivate || OwnerUserId == userId;

    public void EnsureViewableBy(Guid userId)
    {
        if (!CanBeViewedBy(userId))
        {
            throw new ForbiddenException("This portfolio is private to its owner.");
        }
    }
}

/// <summary>
/// A Space curated into a Portfolio. List-level curation is deferred: PortfolioService's rollup query
/// (WorkReportingQueries.PortfolioAsync) groups by Space, not List, so List-granularity membership would
/// need a separate join with no consumer yet.
/// ponytail: Space-only membership; add a ResourceType/ResourceId pair (mirroring Risk.ScopeType) if a
/// List-level curated Portfolio is ever needed.
/// </summary>
public sealed class PortfolioMember : Entity, IWorkspaceOwned
{
    public Guid WorkspaceId { get; private set; }

    private PortfolioMember()
    {
    }

    private PortfolioMember(Guid id, Guid portfolioId, Guid spaceId)
        : base(id)
    {
        PortfolioId = portfolioId;
        SpaceId = spaceId;
    }

    public Guid PortfolioId { get; private set; }
    public Guid SpaceId { get; private set; }

    public static PortfolioMember Create(Guid id, Guid portfolioId, Guid spaceId) => new(id, portfolioId, spaceId);
}
